baseURL: "https://aerialroboticsclub.com/"
languageCode: "en-us"
title: "Aerial Robotics Club"

menu:
  main:
  - name: "About"
    url: "/about/"
    weight: 1

  - name: "Contact"
    url: "/contact/"
    weight: 1

  - name: "Sponsors"
    url: "/sponsors/"
    weight: 1

  - identifier: "systems"
    name: "Systems"
    url: "/systems/"
    weight: 1

  - parent: "systems"
    name: "Kavik"
    url: "/systems/kavik"

  - parent: "systems"
    name: "Fenrir"
    url: "/systems/fenrir/"

  - parent: "systems"
    name: "Akela"
    url: "/systems/akela/"

  - identifier: "member"
    name: "Member Pages"
    weight: 2
    url: "nourl"

  - parent: "member"
    name: "Jira"
    url: "https://jira.aerialroboticsclub.com"

  - parent: "member"
    name: "Redmine"
    url: "https://redmine.aerialroboticsclub.com"
  
  - parent: "member"
    name: "Confluence"
    url: "https://confluence.aerialroboticsclub.com"

params:
  sponsorship:
    levels:
      10: "Supporters"
      20: "Sponsors"
