baseURL = "https://aerialroboticsclub.com/"
languageCode = "en-us"
title = "Aerial Robotics Club"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 1

[[menu.main]]
    name = "Sponsors"
    url = "/sponsors/"
    weight = 1

[[menu.main]]
    identifier = "systems"
    name = "Systems"
    url = "/systems/"
    weight = 1
[[menu.main]]
    parent = "systems"
    name = "Fenrir"
    url = "/systems/fenrir/"
[[menu.main]]
    parent = "systems"
    name = "Akela"
    url = "/systems/akela/"

[[menu.main]]
    identifier = "member"
    name = "Member Pages"
    weight = 2
    url = "nourl"
[[menu.main]]
    parent = "member"
    name = "Internal Progress Tracker"
    url = "/tracker"
[[menu.main]]
    parent = "member"
    name = "Gitea Web Server"
    url = "/gitea"
[[menu.main]]
    parent = "member"
    name = "Documentation"
    url = "/documentation"

[params.sponsorship.levels]
10 = "Supporters"
20 = "Sponsors"
