name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  website:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Authenticate with Github
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/ncsuarc/website:latest
            ghcr.io/ncsuarc/website:${{ github.sha }}
